import Head from 'next/head';
import { ReactNode } from 'react';
import { Provider } from 'react-redux';
import { store } from 'store';

interface ChildrenType {
  children: ReactNode;
}

export default function Layout({ children }: ChildrenType) {
  return (
    <>
      <Head>
        <title>E-Commerce</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Provider store={store}>{children}</Provider>;
    </>
  );
}
