import Head from 'next/head';
import { ReactNode } from 'react';
import { Provider } from 'react-redux';
import { store } from 'store';
import Auth from './auth';

export default function Layout({ children }: { children?: ReactNode }) {
  return (
    <>
      <Head>
        <title>E-Commerce</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Provider store={store}>
        <Auth>{children}</Auth>
      </Provider>
    </>
  );
}
