import Nav from 'components/shared/nav';
import { CartLengthProvider } from 'context/cartLength';
import Head from 'next/head';
import { useRouter } from 'next/router';
import { Provider } from 'react-redux';
import { store } from 'store';
import Auth from './auth';
import Modal from './modal';

export default function Layout({ children }: { children: React.ReactNode }) {
  const router = useRouter();
  const { pathname } = router;

  return (
    <>
      <Head>
        <title>E-Commerce</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Provider store={store}>
        <Modal>
          <Auth>
            <CartLengthProvider>
              {pathname === '/signin' || pathname === '/signup' ? (
                <></>
              ) : (
                <Nav />
              )}
              {children}
            </CartLengthProvider>
          </Auth>
        </Modal>
      </Provider>
    </>
  );
}
